validate:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - uses: flipt-io/setup-action@v0.5.0
      with:
        version: v2 # Installs the latest v2 release
      # Optional, additional arguments to pass to the `flipt` command
      # args:
      # Optional, the directory to run Flipt against, defaults to the repository root
      # working-directory:

    - run: flipt validate
