name: CI   # (optional but recommended)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate-flipt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: flipt-io/setup-action@v0.5.0
        with:
          version: v2 # Installs the latest v2 release

      - run: flipt validate
